# Generated by Django 3.2.15 on 2023-08-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_productobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phonenumber',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='productobject',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
