# Generated by Django 3.2.15 on 2023-08-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230816_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productobject',
            old_name='count',
            new_name='quantity',
        ),
    ]
