# Generated by Django 3.2.15 on 2023-08-17 10:04

from django.db import migrations


def fill_fixed_price(apps, schema_editor):
    ProductObject = apps.get_model('foodcartapp', 'ProductObject')
    product_objects = ProductObject.objects.all()
    for product_object in product_objects.iterator():
        product_object.fixed_price = product_object.product.price
        product_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_productobject_fixed_price'),
    ]

    operations = [
        migrations.RunPython(fill_fixed_price)
    ]


