# Generated by Django 3.2.15 on 2023-08-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230817_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productobject',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Необработанный'), (1, 'В сборке'), (2, 'В доставке'), (3, 'Завершён')], db_index=True, default=0),
        ),
    ]
