# Generated by Django 3.2.15 on 2023-08-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230817_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Необработанный'), (1, 'В сборке'), (2, 'В доставке'), (3, 'Завершён')], db_index=True, default=0, verbose_name='Статус заказа'),
        ),
    ]
